name: site
on:
  push:
    tags:
      - v*

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⏰
        uses: actions/checkout@v2
      - name: install pnpm 8
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 8
      - name: Install and Builld 🔧
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build
      - name: Deploy 🚀
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: .vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}